In [1]:
pip install autoviz

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: autoviz in c:\users\book 1\appdata\roaming\python\python313\site-packages (0.1.905)
Requirement already satisfied: xlrd in c:\users\book 1\appdata\roaming\python\python313\site-packages (from autoviz) (2.0.2)
Requirement already satisfied: wordcloud in c:\users\book 1\appdata\roaming\python\python313\site-packages (from autoviz) (1.9.4)
Requirement already satisfied: emoji in c:\users\book 1\appdata\roaming\python\python313\site-packages (from autoviz) (2.15.0)
Requirement already satisfied: pyamg in c:\users\book 1\appdata\roaming\python\python313\site-packages (from autoviz) (5.3.0)
Requirement already satisfied: scikit-learn in c:\programdata\anaconda3\lib\site-packages (from autoviz) (1.6.1)
Requirement already satisfied: statsmodels in c:\programdata\anaconda3\lib\site-packages (from autoviz) (0.14.4)
Requirement already satisfied: nltk in c:\programdata\anaconda3\lib\site-packages (from autoviz) (3.9.1)
Requirement already satisfied: textblob in c:\users\book 1\appdata\roaming\python\python313\site-packages (from autoviz) (0.19.0)
Requirement already satisfied: xgboost<1.7,>=0.82 in c:\users\book 1\appdata\roaming\python\python313\site-packages (from autoviz) (1.6.2)
Requirement already satisfied: fsspec>=0.8.3 in c:\programdata\anaconda3\lib\site-packages (from autoviz) (2025.3.2)
Requirement already satisfied: typing-extensions>=4.1.1 in c:\programdata\anaconda3\lib\site-packages (from autoviz) (4.12.2)
Requirement already satisfied: pandas-dq>=1.29 in c:\users\book 1\appdata\roaming\python\python313\site-packages (from autoviz) (1.29)
Requirement already satisfied: numpy>=1.24.0 in c:\programdata\anaconda3\lib\site-packages (from autoviz) (2.1.3)
Requirement already satisfied: hvplot>=0.9.2 in c:\programdata\anaconda3\lib\site-packages (from autoviz) (0.11.3)
Requirement already satisfied: holoviews>=1.16.0 in c:\programdata\anaconda3\lib\site-packages (from autoviz) (1.20.2)
Requirement already satisfied: panel>=1.4.0 in c:\programdata\anaconda3\lib\site-packages (from autoviz) (1.7.0)
Requirement already satisfied: pandas>=2.0 in c:\programdata\anaconda3\lib\site-packages (from autoviz) (2.2.3)
Requirement already satisfied: matplotlib>3.7.4 in c:\programdata\anaconda3\lib\site-packages (from autoviz) (3.10.0)
Requirement already satisfied: seaborn>0.12.2 in c:\programdata\anaconda3\lib\site-packages (from autoviz) (0.13.2)
Requirement already satisfied: scipy in c:\programdata\anaconda3\lib\site-packages (from xgboost<1.7,>=0.82->autoviz) (1.15.3)
Requirement already satisfied: bokeh>=3.1 in c:\programdata\anaconda3\lib\site-packages (from holoviews>=1.16.0->autoviz) (3.6.2)
Requirement already satisfied: colorcet in c:\programdata\anaconda3\lib\site-packages (from holoviews>=1.16.0->autoviz) (3.1.0)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from holoviews>=1.16.0->autoviz) (24.2)
Requirement already satisfied: param<3.0,>=2.0 in c:\programdata\anaconda3\lib\site-packages (from holoviews>=1.16.0->autoviz) (2.2.0)
Requirement already satisfied: pyviz-comms>=2.1 in c:\programdata\anaconda3\lib\site-packages (from holoviews>=1.16.0->autoviz) (3.0.2)
Requirement already satisfied: Jinja2>=2.9 in c:\programdata\anaconda3\lib\site-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (3.1.6)
Requirement already satisfied: contourpy>=1.2 in c:\programdata\anaconda3\lib\site-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (1.3.1)
Requirement already satisfied: pillow>=7.1.0 in c:\programdata\anaconda3\lib\site-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (11.1.0)
Requirement already satisfied: PyYAML>=3.10 in c:\programdata\anaconda3\lib\site-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (6.0.2)
Requirement already satisfied: tornado>=6.2 in c:\programdata\anaconda3\lib\site-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (6.5.1)
Requirement already satisfied: xyzservices>=2021.09.1 in c:\programdata\anaconda3\lib\site-packages (from bokeh>=3.1->holoviews>=1.16.0->autoviz) (2022.9.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from Jinja2>=2.9->bokeh>=3.1->holoviews>=1.16.0->autoviz) (3.0.2)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>3.7.4->autoviz) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>3.7.4->autoviz) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>3.7.4->autoviz) (1.4.8)
Requirement already satisfied: pyparsing>=2.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>3.7.4->autoviz) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\programdata\anaconda3\lib\site-packages (from matplotlib>3.7.4->autoviz) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=2.0->autoviz) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas>=2.0->autoviz) (2025.2)
Requirement already satisfied: bleach in c:\programdata\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (6.2.0)
Requirement already satisfied: linkify-it-py in c:\programdata\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (2.0.0)
Requirement already satisfied: markdown in c:\programdata\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (3.8)
Requirement already satisfied: markdown-it-py in c:\programdata\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (2.2.0)
Requirement already satisfied: mdit-py-plugins in c:\programdata\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (0.3.0)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (2.32.3)
Requirement already satisfied: tqdm in c:\programdata\anaconda3\lib\site-packages (from panel>=1.4.0->autoviz) (4.67.1)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib>3.7.4->autoviz) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn->autoviz) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\programdata\anaconda3\lib\site-packages (from scikit-learn->autoviz) (3.5.0)
Requirement already satisfied: webencodings in c:\programdata\anaconda3\lib\site-packages (from bleach->panel>=1.4.0->autoviz) (0.5.1)
Requirement already satisfied: uc-micro-py in c:\programdata\anaconda3\lib\site-packages (from linkify-it-py->panel>=1.4.0->autoviz) (1.0.1)
Requirement already satisfied: mdurl~=0.1 in c:\programdata\anaconda3\lib\site-packages (from markdown-it-py->panel>=1.4.0->autoviz) (0.1.0)
Requirement already satisfied: click in c:\programdata\anaconda3\lib\site-packages (from nltk->autoviz) (8.1.8)
Requirement already satisfied: regex>=2021.8.3 in c:\programdata\anaconda3\lib\site-packages (from nltk->autoviz) (2024.11.6)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from click->nltk->autoviz) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests->panel>=1.4.0->autoviz) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests->panel>=1.4.0->autoviz) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests->panel>=1.4.0->autoviz) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests->panel>=1.4.0->autoviz) (2025.8.3)
Requirement already satisfied: patsy>=0.5.6 in c:\programdata\anaconda3\lib\site-packages (from statsmodels->autoviz) (1.0.1)
Note: you may need to restart the kernel to use updated packages.

In [2]:
pip install matplotlib seaborn

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: matplotlib in c:\programdata\anaconda3\lib\site-packages (3.10.0)
Requirement already satisfied: seaborn in c:\programdata\anaconda3\lib\site-packages (0.13.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (2.1.3)
Requirement already satisfied: packaging>=20.0 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (3.2.0)
Requirement already satisfied: python-dateutil>=2.7 in c:\programdata\anaconda3\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pandas>=1.2 in c:\programdata\anaconda3\lib\site-packages (from seaborn) (2.2.3)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
from autoviz import AutoViz_Class

# Đọc dữ liệu
data = pd.read_csv("C:/Users/BOOK 1/OneDrive/Desktop/Job/marketing_campaign.csv", sep="\t")

# Kiểm tra nhanh
print("Kích thước dữ liệu:", data.shape)
data.head()

Imported v0.1.905. Please call AutoViz in this sequence:
    AV = AutoViz_Class()
    %matplotlib inline
    dfte = AV.AutoViz(filename, sep=',', depVar='', dfte=None, header=0, verbose=1, lowess=False,
               chart_format='svg',max_rows_analyzed=150000,max_cols_analyzed=30, save_plot_dir=None)
Kích thước dữ liệu: (2240, 29)

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,NumDealsPurchases,NumWebPurchases,NumCatalogPurchases,NumStorePurchases,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,88,546,172,88,88,3,8,10,4,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,1,6,2,1,6,2,1,1,2,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,49,127,111,21,42,1,8,2,10,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,4,20,10,3,5,2,2,0,4,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,43,118,46,27,15,5,5,3,6,5,0,0,0,0,0,0,3,11,0

In [5]:
# Khởi tạo AutoViz
AV = AutoViz_Class()

# Tạo báo cáo tự động (EDA)
report = AV.AutoViz(
    "C:/Users/BOOK 1/OneDrive/Desktop/Job/marketing_campaign.csv",  # đường dẫn file
    sep="\t",                # dấu phân tách
    depVar="Response",       # biến mục tiêu
    dfte=None,               # không chia train/test
    header=0, 
    verbose=1,               # in thông tin ra màn hình
    lowess=False, 
    chart_format="svg",      # định dạng đồ thị
    max_rows_analyzed=5000,  # số dòng tối đa để vẽ biểu đồ
    max_cols_analyzed=50     # số cột tối đa
)

Shape of your Data Set loaded: (2240, 29)
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
Classifying variables in data set...
    Number of Numeric Columns =  1
    Number of Integer-Categorical Columns =  15
    Number of String-Categorical Columns =  2
    Number of Factor-Categorical Columns =  0
    Number of String-Boolean Columns =  0
    Number of Numeric-Boolean Columns =  6
    Number of Discrete String Columns =  1
    Number of NLP String Columns =  0
    Number of Date Time Columns =  0
    Number of ID Columns =  1
    Number of Columns to Delete =  2
    28 Predictors classified...
        3 variable(s) removed since they were ID or low-information variables
        List of variables removed: ['ID', 'Z_CostContact', 'Z_Revenue']

################ Binary_Classification problem #####################
To fix these data quality issues in the dataset, import FixDQ from autoviz...
There are 182 duplicate rows in your dataset
    Alert: Dropping duplicate rows can sometimes cause your column data types to change to object!
    All variables classified into correct types.

[nltk_data] Downloading collection 'popular'
[nltk_data]    |
[nltk_data]    | Downloading package cmudict to C:\Users\BOOK
[nltk_data]    |     1\AppData\Roaming\nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package gazetteers to C:\Users\BOOK
[nltk_data]    |     1\AppData\Roaming\nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to C:\Users\BOOK
[nltk_data]    |     1\AppData\Roaming\nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to C:\Users\BOOK
[nltk_data]    |     1\AppData\Roaming\nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package inaugural to C:\Users\BOOK
[nltk_data]    |     1\AppData\Roaming\nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to C:\Users\BOOK
[nltk_data]    |     1\AppData\Roaming\nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package names to C:\Users\BOOK
[nltk_data]    |     1\AppData\Roaming\nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package shakespeare to C:\Users\BOOK
[nltk_data]    |     1\AppData\Roaming\nltk_data...
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package stopwords to C:\Users\BOOK
[nltk_data]    |     1\AppData\Roaming\nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package treebank to C:\Users\BOOK
[nltk_data]    |     1\AppData\Roaming\nltk_data...
[nltk_data]    |   Package treebank is already up-to-date!
[nltk_data]    | Downloading package twitter_samples to C:\Users\BOOK
[nltk_data]    |     1\AppData\Roaming\nltk_data...
[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package omw to C:\Users\BOOK
[nltk_data]    |     1\AppData\Roaming\nltk_data...
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package omw-1.4 to C:\Users\BOOK
[nltk_data]    |     1\AppData\Roaming\nltk_data...
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package wordnet to C:\Users\BOOK
[nltk_data]    |     1\AppData\Roaming\nltk_data...
[nltk_data]    |   Package wordnet is already up-to-date!
[nltk_data]    | Downloading package wordnet2021 to C:\Users\BOOK
[nltk_data]    |     1\AppData\Roaming\nltk_data...
[nltk_data]    |   Package wordnet2021 is already up-to-date!
[nltk_data]    | Downloading package wordnet31 to C:\Users\BOOK
[nltk_data]    |     1\AppData\Roaming\nltk_data...
[nltk_data]    |   Package wordnet31 is already up-to-date!
[nltk_data]    | Downloading package wordnet_ic to C:\Users\BOOK
[nltk_data]    |     1\AppData\Roaming\nltk_data...
[nltk_data]    |   Package wordnet_ic is already up-to-date!
[nltk_data]    | Downloading package words to C:\Users\BOOK
[nltk_data]    |     1\AppData\Roaming\nltk_data...
[nltk_data]    |   Package words is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     C:\Users\BOOK 1\AppData\Roaming\nltk_data...
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package punkt to C:\Users\BOOK
[nltk_data]    |     1\AppData\Roaming\nltk_data...

Could not draw wordcloud plot for Dt_Customer.
Looks like you are missing some required data for this feature.

To download the necessary data, simply run

    python -m textblob.download_corpora

or use the NLTK downloader to download the missing data: http://nltk.org/data.html
If this doesn't fix the problem, file an issue at https://github.com/sloria/TextBlob/issues.

All Plots done
Time to run AutoViz = 7 seconds

 ###################### AUTO VISUALIZATION Completed ########################

[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package snowball_data to C:\Users\BOOK
[nltk_data]    |     1\AppData\Roaming\nltk_data...
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     C:\Users\BOOK 1\AppData\Roaming\nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    |
[nltk_data]  Done downloading collection popular